### ISSUE TITLE
BRepMesh_IncrementalMesh no longer has SetParallel

### ISSUE THREAD

**Issue by pweigel** [DanielWinklehner/py_electrodes#3]
Running (almost) any script in py_electrodes throws this error:
https://gist.github.com/pweigel/a70d7314edcf6aaf4bfe9c4143a031ce

As of https://github.com/tpaviot/pythonocc-core/commit/ce671d360676aa3750c856c4d8252383bc897528#diff-2ff913e0b4c51a7aa7e6bf1a07be2b87 pythonocc has removed the ability to set multi-threading like this (versions 7.4.0+). Maybe mesh.SetParallelDefault(True) is the fix?

**Comment by DanielWinklehner** [comment]
I noticed this as well, but had no time to look into it. If it works with your suggestion, create a pull request ;)

**Comment by pweigel** [comment]
Decided to push it to the master since it was just one line (and a version change) in https://github.com/DanielWinklehner/py_electrodes/commit/6925462a3be428cca81071a73e91766d0002f6d5.

This was also done in https://github.com/tpaviot/pythonocc-demos/commit/6d5e60ad34b70df11f8a0d4b293097512e8af074#diff-da088270d83167d65f65efde45a7e00f, which may be a good reference for any other problems that come up.

**Comment by DanielWinklehner** [comment]
Great, thanks!
